services:
  cognito.sqlserver:
    container_name: cognito.sqlserver
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Pass123$
      MSSQL_PID: Enterprise
    volumes:
      - sqlserverdata:/var/opt/mssql

  cognito.cache.redis:
    container_name: cognito.cache.redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --maxmemory-policy
      - noeviction
      - --timeout
      - "0"
    volumes:
      - cache:/data

volumes:
  sqlserverdata:
  cache:
    driver: local