spring:
  application:
    name: galactus-api

  graphql:
    graphiql:
      enabled: true
    http:
      path: /graphql
    cors:
      allowed-methods: "*"
      allowed-origins: "*"
      max-age: 1800s

  datasource:
    url: jdbc:sqlserver://;serverName=localhost;databaseName=galactusdb;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Pass123$
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

server:
  port: 8065
  servlet:
    context-path: /
