spring:
  application:
    name: galactus-api

  graphql:
    graphiql:
      enabled: true
    http:
      path: /graphql
    cors:
      allowed-methods: "*"
      allowed-origins: "*"
      max-age: 1800s

  datasource:
    url: jdbc:sqlserver://;serverName=localhost;databaseName=galactusdb;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.hibernate.SpringImplicitNamingStrategy

    open-in-view: false

  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workers-auto-discovery:
      packages: com.galactus


server:
  port: 8065
  servlet:
    context-path: /

logging:
  level:
    com.galactus: DEBUG
    root: INFO

archaius:
  dynamic-url: ${DYNAMIC_URL}
  # dynamic-url: "file:/etc/galactus/galactus-dynamic.properties" # Linux example
  # dynamic-url: "file:///F:/Java/galactus-api/src/main/resources/config.properties" # windows example
  polling-interval: 5s
  defaults:
    app.name: "galactus-api"
    app.feature.toggle: "true"
